apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      # 优雅停止
      terminationGracePeriodSeconds: 30
      containers:
        - name: order
          image: evanchn/order:v1.0
          resources:
            limits:
              cpu: 500m
              memory: 200Mi
            requests:
              cpu: 200m
              memory: 100Mi
          envFrom:
            - configMapRef:
                name: apps-config
          # 探针检测 & 优雅启动
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 3
            timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: order
spec:
  selector:
    app: order
  ports:
    - port: 8083
      targetPort: 8083
