package configs

var JWTPublicKey = `-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDYwsa7uBS4VbdGDpvs4zLkNVbZ
4c/9wvh9Odh3h5xNGzMN7+DZRhnpEfoAU0IO3wvw1lMs/aBk7r6rXtJ4fYsaLX6U
ffXIVpRhUYDyluRTmytA6w0ZQEMJqekTsDA4RQi8lCWs2o7jS9PRaiUpIpWrSqwd
wNBZkZVj3ggastVB1QIDAQAB
-----END PUBLIC KEY-----`
